In [1]:
import pandas as pd
import numpy as np

In [12]:
!pip install psycopg2

Collecting psycopg2
  Downloading psycopg2-2.9.11-cp312-cp312-win_amd64.whl.metadata (5.1 kB)
Downloading psycopg2-2.9.11-cp312-cp312-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.7 MB 1.1 MB/s eta 0:00:02
   ----------- ---------------------------- 0.8/2.7 MB 1.2 MB/s eta 0:00:02
   --------------- ------------------------ 1.0/2.7 MB 1.2 MB/s eta 0:00:02
   ------------------- -------------------- 1.3/2.7 MB 1.3 MB/s eta 0:00:02
   ----------------------- ---------------- 1.6/2.7 MB 1.4 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.5 MB/s eta 0:00:01
   -------------------------------------- - 2.6/2.7 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 1.6 MB/s eta 0:00:00
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.11

WARNING: Ignoring invalid distribution ~upyterlab (D:\Anaconda\Lib\site-packages)
WARNING: Ignoring invalid distribution ~upyterlab (D:\Anaconda\Lib\site-packages)
WARNING: Ignoring invalid distribution ~upyterlab (D:\Anaconda\Lib\site-packages)

# ТЗ

Проблема

На текущем варианте лендинга пользователь сначала выбирает ритейлера, переходит в каталог, ищет нужные ему товары и только потом может узнать, что по его адресу выбранного магазина может не оказаться. Хотим проверить гипотезу, что выбор адреса до этапа выбора магазина поможет избежать “кривых” сценариев без повышения отказов с самого лендинга.

Описание групп

1 - контрольная (без каких-либо изменений)
2 - тестовая, сначала пользователь указывает адрес, затем выбирает магазин. 

Метрики

Основные метрики, на основе которых будем принимать решение:

- bounce rate лендинга (в тестовых группах он не должен стат значимо вырасти)
- конверсия в добавление в корзину

# Подключение к серверу SQL

In [2]:
import psycopg2

Данные для доступа на сервер (PostgreSQL).

DBNAME='sbermarket-test'

USER='rouser'

PASSWORD='ZI6MVnmi'

HOST='178.62.242.91'

PORT=5433

In [4]:
from sqlalchemy import create_engine
con = create_engine('postgresql+psycopg2://rouser:ZI6MVnmi@178.62.242.91:5433/sbermarket-test')

In [8]:
def select(sql):
  return pd.read_sql(sql,con)

In [10]:
sql = ''' select 1 '''

In [12]:
select(sql)

OperationalError: (psycopg2.OperationalError) connection to server at "178.62.242.91", port 5433 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

# Загрузка данных

In [18]:
AB_Test_Hit = pd.read_csv('Career Factory/AB Test Hit.csv')

In [54]:
Product_Added = pd.read_csv('Career Factory/Product Added.csv')

In [105]:
Product_Added.columns = ['_timestamp', 'anonymous_id']

In [192]:
Landing_Viewed = pd.read_csv('Career Factory/Landing Viewed.csv')

In [19]:
AB_Test_Hit.columns = ['hit_at', 'anonymous_id', '_group', 'device_type', 'browser', 'os']

In [20]:
AB_Test_Hit.head()

,hit_at,anonymous_id,_group,device_type,browser,os
0,2020-11-30 04:21:38.616 UTC,3e05a2dc-3922-4caf-b837-08fcb337c82e,default,desktop,IE,Windows
1,2020-12-01 20:24:04.363 UTC,7f00b6ca-7938-4866-a323-c520838f5ef9,default,desktop,IE,Windows
2,2020-11-28 20:16:52.901 UTC,91e9900e-2cc6-4362-92b4-9e6712a6918e,address_first,desktop,IE,Windows
3,2020-11-29 13:29:40.557 UTC,616dd5e8-dee2-47aa-9d80-0dfadcf1922f,default,desktop,IE,Windows
4,2020-11-27 14:56:29.471 UTC,64734da4-d9f3-4d53-b401-4d0819a6e5fb,default,desktop,IE,Windows

In [24]:
#AB_Test_Hit['hit_at'] = pd.to_datetime(AB_Test_Hit['hit_at'], format='%Y-%m-%d %H:%M:%S.%f')

# Загрузка данных в SQL

In [27]:
import sqlite3

In [29]:
# Установить соединение с файлом БД
conn = sqlite3.connect('db')

In [31]:
#Создать курсор
cur = conn.cursor()

In [33]:
# функция для вызова sql запроса
def select(sql):
  return pd.read_sql(sql,conn)

In [35]:
AB_Test_Hit.to_sql('AB_Test_Hit', conn, index=False, if_exists='replace')

502784

In [107]:
# таблица с Время фактического добавления товара в корзину
Product_Added.to_sql('Product_Added', conn, index=False, if_exists='replace')

1150060

In [194]:
Landing_Viewed.to_sql('Landing_Viewed', conn, index=False, if_exists='replace')

341481

In [36]:
sql = ''' SELECT * FROM AB_Test_Hit LIMIT 5'''

In [37]:
select(sql)

,hit_at,anonymous_id,_group,device_type,browser,os
0,2020-11-30 04:21:38.616 UTC,3e05a2dc-3922-4caf-b837-08fcb337c82e,default,desktop,IE,Windows
1,2020-12-01 20:24:04.363 UTC,7f00b6ca-7938-4866-a323-c520838f5ef9,default,desktop,IE,Windows
2,2020-11-28 20:16:52.901 UTC,91e9900e-2cc6-4362-92b4-9e6712a6918e,address_first,desktop,IE,Windows
3,2020-11-29 13:29:40.557 UTC,616dd5e8-dee2-47aa-9d80-0dfadcf1922f,default,desktop,IE,Windows
4,2020-11-27 14:56:29.471 UTC,64734da4-d9f3-4d53-b401-4d0819a6e5fb,default,desktop,IE,Windows

# Число пользователей и уникальных пользователей

In [42]:
sql = '''
        SELECT t._group, count(anonymous_id) AS cnt,
        count(distinct anonymous_id) AS unique_cnt
        FROM AB_Test_Hit t
        group by t._group
        '''

In [44]:
select(sql)

          _group     cnt  unique_cnt
0  address_first   56310       54820
1        default  446474      434727

# Период эксперимента

In [46]:
sql = '''
        SELECT min(t.hit_at) as min,
               max(t.hit_at) as max
        FROM AB_Test_Hit t
        '''

In [47]:
select(sql)

                           min                          max
0  2020-11-26 00:00:10.318 UTC  2020-12-10 23:59:57.308 UTC

# Конверсия

## Необходимые таблицы

In [109]:
sql = ''' SELECT * FROM Product_Added LIMIT 5
            '''

In [111]:
#timestamp - Время фактического добавления товара в корзину
select(sql)

                    _timestamp                          anonymous_id
0  2020-12-09 20:51:32.429 UTC  e2d50ef1-0667-4da4-88ef-ecbdd7c6a73a
1  2020-12-09 19:39:10.216 UTC  bb5ca977-97f4-4ec8-8a71-fe206108917b
2  2020-12-09 21:53:08.999 UTC  8e965f2b-7da0-4efb-84f5-f205956e8c30
3  2020-12-09 19:46:22.307 UTC  bb5ca977-97f4-4ec8-8a71-fe206108917b
4  2020-12-09 22:16:13.379 UTC  8e965f2b-7da0-4efb-84f5-f205956e8c30

In [125]:
sql = '''
        SELECT min(t._timestamp) as min,
               max(t._timestamp) as max
        FROM Product_Added t
        '''

In [127]:
select(sql)

                           min                          max
0  2020-11-26 00:00:00.121 UTC  2020-12-17 23:21:36.489 UTC

In [113]:
sql = ''' SELECT * FROM AB_Test_Hit LIMIT 5'''

In [115]:
# timestamp, когда пользователь был определен в группу эксперимента
select(sql)

,hit_at,anonymous_id,_group,device_type,browser,os
0,2020-11-30 04:21:38.616 UTC,3e05a2dc-3922-4caf-b837-08fcb337c82e,default,desktop,IE,Windows
1,2020-12-01 20:24:04.363 UTC,7f00b6ca-7938-4866-a323-c520838f5ef9,default,desktop,IE,Windows
2,2020-11-28 20:16:52.901 UTC,91e9900e-2cc6-4362-92b4-9e6712a6918e,address_first,desktop,IE,Windows
3,2020-11-29 13:29:40.557 UTC,616dd5e8-dee2-47aa-9d80-0dfadcf1922f,default,desktop,IE,Windows
4,2020-11-27 14:56:29.471 UTC,64734da4-d9f3-4d53-b401-4d0819a6e5fb,default,desktop,IE,Windows

## Join таблиц

`Есть таблица юзеров с их id. Делаем лефт джоин таблицы с юзерами, которые добавили товар в корзину. Если запись для юзера из второй таблицы не null значит юзер, участвующий в эксперименте, добавил товар в корзину`

In [179]:
sql = ''' SELECT t.hit_at, t.anonymous_id, t._group, pa.anonymous_id, pa._timestamp,
          CASE
              WHEN pa.anonymous_id IS NOT NULL THEN 1 ELSE 0
          END AS product_added
          FROM AB_Test_Hit t
          LEFT JOIN Product_Added pa ON t.anonymous_id = pa.anonymous_id AND
          pa._timestamp >= t.hit_at -- фильтруем тех, кто добавил в корзину раньше начала эксперимента, 
          --хотя есть такие _timestamp, которые уже после завершения эскперимента ???
          WHERE product_added = 1
            '''

In [181]:
select(sql)

,hit_at,anonymous_id,_group,anonymous_id,_timestamp,product_added
0,2020-12-06 21:29:21.894 UTC,0a3947e5-23e9-4bf0-bf48-e59b87ef89e9,default,0a3947e5-23e9-4bf0-bf48-e59b87ef89e9,2020-12-06 21:37:56.467 UTC,1
1,2020-12-06 14:26:40.681 UTC,8e31496a-582f-4620-b0de-53ada91fe845,default,8e31496a-582f-4620-b0de-53ada91fe845,2020-12-06 14:41:53.285 UTC,1
2,2020-12-06 14:26:40.681 UTC,8e31496a-582f-4620-b0de-53ada91fe845,default,8e31496a-582f-4620-b0de-53ada91fe845,2020-12-06 14:42:32.157 UTC,1
3,2020-12-06 14:26:40.681 UTC,8e31496a-582f-4620-b0de-53ada91fe845,default,8e31496a-582f-4620-b0de-53ada91fe845,2020-12-06 14:44:55.6 UTC,1
4,2020-12-06 14:26:40.681 UTC,8e31496a-582f-4620-b0de-53ada91fe845,default,8e31496a-582f-4620-b0de-53ada91fe845,2020-12-06 14:46:36.002 UTC,1
...,...,...,...,...,...,...
1252928,2020-12-09 00:02:26.482 UTC,5a90a457-fec0-44b5-92a4-0044abc78e3a,default,5a90a457-fec0-44b5-92a4-0044abc78e3a,2020-12-09 22:59:00.049 UTC,1
1252929,2020-12-09 00:02:26.482 UTC,5a90a457-fec0-44b5-92a4-0044abc78e3a,default,5a90a457-fec0-44b5-92a4-0044abc78e3a,2020-12-09 23:40:41.496 UTC,1
1252930,2020-12-09 00:02:26.482 UTC,5a90a457-fec0-44b5-92a4-0044abc78e3a,default,5a90a457-fec0-44b5-92a4-0044abc78e3a,2020-12-09 23:41:18.615 UTC,1
1252931,2020-12-09 00:02:26.482 UTC,5a90a457-fec0-44b5-92a4-0044abc78e3a,default,5a90a457-fec0-44b5-92a4-0044abc78e3a,2020-12-11 14:25:30.392 UTC,1
1252932,2020-12-10 03:17:56.293 UTC,05927aa8-3b4c-472d-92c9-eae7a6832bec,default,05927aa8-3b4c-472d-92c9-eae7a6832bec,2020-12-10 03:20:22.528 UTC,1

## Считаем конверсию

In [185]:
sql = ''' 
        WITH conv AS (
          SELECT t.hit_at, t.anonymous_id, t._group,
          MAX(CASE
                  WHEN pa.anonymous_id IS NOT NULL THEN 1 ELSE 0
              END) AS product_added -- по сути убирает дубли (см. выше). Т.е. остается на одного юзера одно добавление в корзину.
          FROM AB_Test_Hit t
          LEFT JOIN Product_Added pa ON t.anonymous_id = pa.anonymous_id AND
          pa._timestamp >= t.hit_at
          GROUP BY t.hit_at, t.anonymous_id, t._group)

          SELECT t._group, COUNT(*) as cnt, SUM(product_added) AS product_added, AVG(product_added) AS cr
          FROM conv t
          GROUP BY t._group
      '''

In [187]:
select(sql)

          _group     cnt  product_added        cr
0  address_first   56310           5888  0.104564
1        default  446474          42929  0.096151

# Проверка значимости 
https://www.evanmiller.org/ab-testing/chi-squared.html#!5888/56310;42929/446474@95

# Конверсия в лэндинг

`Считаем тех пользователей из двух групп, которые видели лэндинг`

In [197]:
sql = ''' SELECT * FROM Landing_Viewed '''

In [199]:
select(sql)

                          timestamp                          anonymous_id
0       2020-12-05 10:01:51.305 UTC  00001104-4c72-4f48-bb8c-ace2ded63f8b
1       2020-12-08 11:07:39.962 UTC  00007575-88d6-4acc-9940-e9ccb8358dca
2       2020-12-03 13:12:37.952 UTC  00016e45-138b-401e-9eac-78b92d48c6c4
3       2020-12-02 16:03:37.548 UTC  0001814e-5cf7-4d23-bc95-4630d9152fc1
4       2020-12-01 08:24:51.787 UTC  00021d91-c65e-4049-9ae1-7d64702c8c12
...                             ...                                   ...
341476  2020-12-05 14:54:01.768 UTC  fffedf6a-7be6-4313-a0d9-ff87463ba6e8
341477  2020-12-10 10:47:30.204 UTC  fffee334-8e5d-4923-b97e-c3ebb060d70b
341478  2020-12-04 19:15:55.857 UTC  fffee334-8e5d-4923-b97e-c3ebb060d70b
341479   2020-12-07 06:11:38.61 UTC  ffff53e1-df50-43dd-a1d3-c2e34271920b
341480  2020-12-04 09:25:11.986 UTC  ffffdd92-2f11-4455-8cd1-c065d368b120

[341481 rows x 2 columns]

In [215]:
sql = ''' 
    WITH conv AS (
          SELECT t.hit_at, t.anonymous_id, t._group,
          MAX(CASE
                  WHEN lv.anonymous_id IS NOT NULL THEN 1 ELSE 0
              END) AS landing_viewed-- по сути убирает дубли (см. выше). Т.е. остается на одного юзера один просмотр лендинга
          FROM AB_Test_Hit t
          LEFT JOIN Landing_Viewed lv ON t.anonymous_id = lv.anonymous_id AND
          lv.timestamp >= t.hit_at
          GROUP BY t.hit_at, t.anonymous_id, t._group)

         SELECT t._group, COUNT(*) as cnt, SUM(t.landing_viewed) AS landing_viewed, AVG(landing_viewed) AS cr
         FROM conv t
         GROUP BY t._group
      '''

In [217]:
select(sql)

          _group     cnt  landing_viewed        cr
0  address_first   56310           18565  0.329693
1        default  446474          148655  0.332953

# Считаем пользователей, которые видели лэндинг и добавили товар в корзину

`Пользователи, которые видели лэндинг`

In [246]:
sql = '''
    WITH conv AS (
          SELECT t.hit_at, t.anonymous_id, t._group,
          MIN(lv.timestamp) AS Landing_Viewed_ts
          FROM AB_Test_Hit t
          INNER JOIN Landing_Viewed lv ON t.anonymous_id = lv.anonymous_id AND
          lv.timestamp >= t.hit_at
          GROUP BY t.hit_at, t.anonymous_id, t._group) 
          
    SELECT *
    FROM conv t 
    '''

In [248]:
select(sql)

,hit_at,anonymous_id,_group,Landing_Viewed_ts
0,2020-11-26 00:00:25.857 UTC,e9480708-34a6-4356-8e65-b39664875cb9,default,2020-11-26 00:00:25.888 UTC
1,2020-11-26 00:01:33.215 UTC,5ddc6caf-59f0-451c-b5ed-8c52548a67f9,default,2020-11-26 00:01:33.352 UTC
2,2020-11-26 00:01:43.855 UTC,5e56d5cc-8105-418e-b988-a7e38a0ef5ca,default,2020-11-26 00:01:43.947 UTC
3,2020-11-26 00:01:56.167 UTC,46a360bc-b4d4-4ccd-827e-07c9edd642d5,default,2020-11-26 00:01:56.17 UTC
4,2020-11-26 00:02:11.672 UTC,5ef12423-e3f0-4ba6-b5de-6b1fef66e0fb,default,2020-11-26 00:02:11.672 UTC
...,...,...,...,...
167215,2020-12-10 23:57:06.195 UTC,91103267-87dc-4c49-869a-ed366677541f,default,2020-12-10 23:57:06.195 UTC
167216,2020-12-10 23:57:18.759 UTC,fd857b34-f894-471c-a216-1b62abf44da3,default,2020-12-10 23:57:18.759 UTC
167217,2020-12-10 23:58:10.631 UTC,d7c4b510-3cb1-4408-9a5b-a69b613c24c9,address_first,2020-12-10 23:58:10.632 UTC
167218,2020-12-10 23:58:55.288 UTC,251fb875-745b-4acd-8943-527cc0c518ef,default,2020-12-10 23:58:55.289 UTC
167219,2020-12-10 23:59:57.308 UTC,49ec0fa2-3470-4bad-b2ec-87341eeec530,default,2020-12-10 23:59:58.201 UTC

`Пользователи, которые видели лэндинг и добавили товар в корзину`

In [269]:
sql = '''
    WITH conv AS (
          SELECT t.hit_at, t.anonymous_id, t._group,
          MIN(lv.timestamp) AS Landing_Viewed_ts
          FROM AB_Test_Hit t
          INNER JOIN Landing_Viewed lv ON t.anonymous_id = lv.anonymous_id AND
          lv.timestamp >= t.hit_at
          GROUP BY t.hit_at, t.anonymous_id, t._group),

          conv2 AS (
          SELECT c.hit_at, c.anonymous_id, c._group,
          MAX(CASE
                  WHEN pa.anonymous_id IS NOT NULL THEN 1 ELSE 0
              END) AS product_added
          FROM conv c 
          LEFT JOIN Product_Added pa ON c.anonymous_id = pa.anonymous_id AND
          pa._timestamp >= c.Landing_Viewed_ts
          GROUP BY c.hit_at, c.anonymous_id, c._group
          )

    SELECT *
    FROM conv2 t
    LIMIT 5
      '''

In [271]:
select(sql)

,hit_at,anonymous_id,_group,product_added
0,2020-11-26 00:00:25.857 UTC,e9480708-34a6-4356-8e65-b39664875cb9,default,0
1,2020-11-26 00:01:33.215 UTC,5ddc6caf-59f0-451c-b5ed-8c52548a67f9,default,0
2,2020-11-26 00:01:43.855 UTC,5e56d5cc-8105-418e-b988-a7e38a0ef5ca,default,0
3,2020-11-26 00:01:56.167 UTC,46a360bc-b4d4-4ccd-827e-07c9edd642d5,default,0
4,2020-11-26 00:02:11.672 UTC,5ef12423-e3f0-4ba6-b5de-6b1fef66e0fb,default,0

In [273]:
sql = '''
    WITH conv AS (
          SELECT t.hit_at, t.anonymous_id, t._group,
          MIN(lv.timestamp) AS Landing_Viewed_ts
          FROM AB_Test_Hit t
          INNER JOIN Landing_Viewed lv ON t.anonymous_id = lv.anonymous_id AND
          lv.timestamp >= t.hit_at
          GROUP BY t.hit_at, t.anonymous_id, t._group),

          conv2 AS (
          SELECT c.hit_at, c.anonymous_id, c._group,
          MAX(CASE
                  WHEN pa.anonymous_id IS NOT NULL THEN 1 ELSE 0
              END) AS product_added
          FROM conv c 
          LEFT JOIN Product_Added pa ON c.anonymous_id = pa.anonymous_id AND
          pa._timestamp >= c.Landing_Viewed_ts
          GROUP BY c.hit_at, c.anonymous_id, c._group
          )

    SELECT t._group, COUNT(*), SUM(t.product_added) AS product_added, AVG(t.product_added) as cr
    FROM conv2 t
    GROUP BY t._group
      '''

In [275]:
select(sql)

          _group  COUNT(*)  product_added        cr
0  address_first     18565           3180  0.171290
1        default    148655          21865  0.147086

`Таким образом, у тех пользователей которые видели лэндинг конверсия добавления в корзину выше`

# Есть ли пересечения в двух группах

In [315]:
sql = ''' SELECT anonymous_id, count(_group) as cnt_group
          FROM AB_Test_Hit
          group by anonymous_id
          having cnt_group >=2
          order by cnt_group desc
          '''

In [317]:
select(sql)

                               anonymous_id  cnt_group
0      5bb785fd-e0e7-447a-b0e1-a06328b31cbe         18
1      bcaa113d-c128-443f-9ede-2736847e1969         15
2      1dea1cc9-72c0-4bee-bdb6-c59faacd72ba         15
3      06eaec3d-511a-4794-92ea-a19efaaf7f19         15
4      ba5239f5-1115-4caa-aef2-242a9c039b12         14
...                                     ...        ...
11115  000ab593-0c03-4a9d-b169-0661dd453678          2
11116  0006d07d-d6f7-4e3b-a661-3c06433148a6          2
11117  0005ddf1-b16f-4836-a4cb-7e63aebde8ff          2
11118  000544b6-143b-4c9c-a2eb-d4e99fb4b89f          2
11119  00000782-154a-4159-ab12-6c34b658e375          2

[11120 rows x 2 columns]

In [319]:
sql = ''' SELECT anonymous_id, count(distinct _group) as cnt_group
          FROM AB_Test_Hit
          group by anonymous_id
          having cnt_group >=2
          order by cnt_group desc
          '''

In [321]:
select(sql)

                             anonymous_id  cnt_group
0    fffa252e-811f-4cca-9a90-6b850098704c          2
1    ff947c59-7802-45cd-bc30-8a577135d584          2
2    ff65919d-3c4d-467e-b2b2-0cde92ad3e06          2
3    ff029d19-46d3-47d1-83a5-65126aad3a51          2
4    fef6ddc4-1b30-4a5c-a16c-c8851b26bf61          2
..                                    ...        ...
523  00998353-1778-4cb3-876f-8a1e110c8e7a          2
524  009615c6-aadf-4c79-a0d9-2b0fa5e4bf09          2
525  008dbd14-e52f-4a59-b3ce-4655526c32a6          2
526  00687c2a-5eea-4b21-befb-c507b75db12e          2
527  0045db67-ef5c-4a6b-81b4-3e079d79b073          2

[528 rows x 2 columns]

In [331]:
f'{(528 / (56310+446474))*100}%'

'0.1050152749490835%'

`тут шум по сути`

# Группировки по девайсам, браузеру, ОС

Смотрим, чтобы не было перекосов

## device_type

In [36]:
sql = ''' SELECT * FROM AB_Test_Hit LIMIT 5'''

In [37]:
select(sql)

,hit_at,anonymous_id,_group,device_type,browser,os
0,2020-11-30 04:21:38.616 UTC,3e05a2dc-3922-4caf-b837-08fcb337c82e,default,desktop,IE,Windows
1,2020-12-01 20:24:04.363 UTC,7f00b6ca-7938-4866-a323-c520838f5ef9,default,desktop,IE,Windows
2,2020-11-28 20:16:52.901 UTC,91e9900e-2cc6-4362-92b4-9e6712a6918e,address_first,desktop,IE,Windows
3,2020-11-29 13:29:40.557 UTC,616dd5e8-dee2-47aa-9d80-0dfadcf1922f,default,desktop,IE,Windows
4,2020-11-27 14:56:29.471 UTC,64734da4-d9f3-4d53-b401-4d0819a6e5fb,default,desktop,IE,Windows

In [348]:
sql = '''
    WITH conv AS (
          SELECT t.hit_at, t.anonymous_id, t._group, t.device_type, t.browser, t.os,
          MIN(lv.timestamp) AS Landing_Viewed_ts
          FROM AB_Test_Hit t
          INNER JOIN Landing_Viewed lv ON t.anonymous_id = lv.anonymous_id AND
          lv.timestamp >= t.hit_at
          GROUP BY t.hit_at, t.anonymous_id, t._group, t.device_type, t.browser, t.os),

          conv2 AS (
          SELECT c.hit_at, c.anonymous_id, c._group, c.device_type, c.browser, c.os,
          MAX(CASE
                  WHEN pa.anonymous_id IS NOT NULL THEN 1 ELSE 0
              END) AS product_added
          FROM conv c 
          LEFT JOIN Product_Added pa ON c.anonymous_id = pa.anonymous_id AND
          pa._timestamp >= c.Landing_Viewed_ts
          GROUP BY c.hit_at, c.anonymous_id, c._group, c.device_type, c.browser, c.os
          )

    SELECT *
    FROM conv2 t
    limit 5
      '''

In [350]:
select(sql)

,hit_at,anonymous_id,_group,device_type,browser,os,product_added
0,2020-11-26 00:00:25.857 UTC,e9480708-34a6-4356-8e65-b39664875cb9,default,mobile,Chrome,Android,0
1,2020-11-26 00:01:33.215 UTC,5ddc6caf-59f0-451c-b5ed-8c52548a67f9,default,desktop,Chrome,Mac OS,0
2,2020-11-26 00:01:43.855 UTC,5e56d5cc-8105-418e-b988-a7e38a0ef5ca,default,mobile,MIUI Browser,Android,0
3,2020-11-26 00:01:56.167 UTC,46a360bc-b4d4-4ccd-827e-07c9edd642d5,default,mobile,Chrome,Android,0
4,2020-11-26 00:02:11.672 UTC,5ef12423-e3f0-4ba6-b5de-6b1fef66e0fb,default,mobile,Samsung Browser,Android,0

In [388]:
sql = '''
    WITH conv AS (
          SELECT t.hit_at, t.anonymous_id, t._group, t.device_type, t.browser, t.os,
          MIN(lv.timestamp) AS Landing_Viewed_ts
          FROM AB_Test_Hit t
          INNER JOIN Landing_Viewed lv ON t.anonymous_id = lv.anonymous_id AND
          lv.timestamp >= t.hit_at
          GROUP BY t.hit_at, t.anonymous_id, t._group, t.device_type, t.browser, t.os),

          conv2 AS (
          SELECT c.hit_at, c.anonymous_id, c._group, c.device_type, c.browser, c.os,
          MAX(CASE
                  WHEN pa.anonymous_id IS NOT NULL THEN 1 ELSE 0
              END) AS product_added
          FROM conv c 
          LEFT JOIN Product_Added pa ON c.anonymous_id = pa.anonymous_id AND
          pa._timestamp >= c.Landing_Viewed_ts
          GROUP BY c.hit_at, c.anonymous_id, c._group, c.device_type, c.browser, c.os
          ),

          cnt_in_group AS
          (SELECT t._group, t.device_type, count(*) as cnt
          FROM conv2 t
          GROUP BY t._group, t.device_type)

          SELECT t.*, 
          SUM(t.cnt) OVER(PARTITION BY _group) AS total,
          CAST(t.cnt AS REAL)/CAST((SUM(t.cnt) OVER(PARTITION BY t._group)) AS REAL) AS percent_of_total
          FROM cnt_in_group t
          '''

In [390]:
select(sql)

          _group device_type    cnt   total  percent_of_total
0  address_first     console      1   18565          0.000054
1  address_first     desktop   8569   18565          0.461567
2  address_first      mobile   9736   18565          0.524428
3  address_first     smarttv      1   18565          0.000054
4  address_first      tablet    258   18565          0.013897
5        default     console      5  148655          0.000034
6        default     desktop  69353  148655          0.466537
7        default      mobile  77231  148655          0.519532
8        default     smarttv      7  148655          0.000047
9        default      tablet   2059  148655          0.013851

`По девайсам перекоса нет, примерно 50 на 50 это desktop и mobile`

## browser

In [396]:
sql = '''
    WITH conv AS (
          SELECT t.hit_at, t.anonymous_id, t._group, t.device_type, t.browser, t.os,
          MIN(lv.timestamp) AS Landing_Viewed_ts
          FROM AB_Test_Hit t
          INNER JOIN Landing_Viewed lv ON t.anonymous_id = lv.anonymous_id AND
          lv.timestamp >= t.hit_at
          GROUP BY t.hit_at, t.anonymous_id, t._group, t.device_type, t.browser, t.os),

          conv2 AS (
          SELECT c.hit_at, c.anonymous_id, c._group, c.device_type, c.browser, c.os,
          MAX(CASE
                  WHEN pa.anonymous_id IS NOT NULL THEN 1 ELSE 0
              END) AS product_added
          FROM conv c 
          LEFT JOIN Product_Added pa ON c.anonymous_id = pa.anonymous_id AND
          pa._timestamp >= c.Landing_Viewed_ts
          GROUP BY c.hit_at, c.anonymous_id, c._group, c.device_type, c.browser, c.os
          ),

          cnt_in_group AS
          (SELECT t._group, t.browser, count(*) as cnt
          FROM conv2 t
          GROUP BY t._group, t.browser)

          SELECT t.*, 
          SUM(t.cnt) OVER(PARTITION BY _group) AS total,
          CAST(t.cnt AS REAL)/CAST((SUM(t.cnt) OVER(PARTITION BY t._group)) AS REAL) AS percent_of_total
          FROM cnt_in_group t
          '''

In [398]:
select(sql)

           _group          browser    cnt   total  percent_of_total
0   address_first  Android Browser     14   18565          0.000754
1   address_first           Chrome  10961   18565          0.590412
2   address_first   Chrome WebView    121   18565          0.006518
3   address_first         Chromium      3   18565          0.000162
4   address_first             Edge    245   18565          0.013197
5   address_first         Facebook      4   18565          0.000215
6   address_first          Firefox    504   18565          0.027148
7   address_first              GSA     92   18565          0.004956
8   address_first               IE      2   18565          0.000108
9   address_first         IEMobile      1   18565          0.000054
10  address_first     MIUI Browser    351   18565          0.018907
11  address_first          Maxthon      6   18565          0.000323
12  address_first    Mobile Safari   2680   18565          0.144358
13  address_first            Opera    478   18565          0.025747
14  address_first      Opera Touch      6   18565          0.000323
15  address_first         PaleMoon      1   18565          0.000054
16  address_first           Puffin      1   18565          0.000054
17  address_first           Safari    315   18565          0.016967
18  address_first  Samsung Browser    527   18565          0.028387
19  address_first        SeaMonkey      1   18565          0.000054
20  address_first        UCBrowser      8   18565          0.000431
21  address_first           WebKit     58   18565          0.003124
22  address_first           Yandex   2186   18565          0.117748
23        default  Android Browser    114  148655          0.000767
24        default            Brave      1  148655          0.000007
25        default           Chrome  87878  148655          0.591154
26        default   Chrome WebView    895  148655          0.006021
27        default         Chromium     10  148655          0.000067
28        default             Edge   2036  148655          0.013696
29        default         Facebook     36  148655          0.000242
30        default          Firefox   4243  148655          0.028543
31        default              GSA    645  148655          0.004339
32        default               IE     35  148655          0.000235
33        default        IceDragon      1  148655          0.000007
34        default        Iceweasel      1  148655          0.000007
35        default     MIUI Browser   2697  148655          0.018143
36        default          Maxthon     18  148655          0.000121
37        default    Mobile Safari  21221  148655          0.142753
38        default          Mozilla      4  148655          0.000027
39        default            Opera   3746  148655          0.025199
40        default      Opera Touch     27  148655          0.000182
41        default         PaleMoon      2  148655          0.000013
42        default           Puffin     13  148655          0.000087
43        default        QQBrowser      1  148655          0.000007
44        default           Safari   2646  148655          0.017800
45        default  Samsung Browser   4222  148655          0.028401
46        default             Slim      1  148655          0.000007
47        default        UCBrowser    105  148655          0.000706
48        default          Vivaldi      5  148655          0.000034
49        default         Waterfox      2  148655          0.000013
50        default           WeChat      1  148655          0.000007
51        default           WebKit    521  148655          0.003505
52        default           Yandex  17527  148655          0.117904
53        default          jasmine      1  148655          0.000007

In [400]:
t = select(sql)

In [406]:
t.pivot_table(index='browser', columns='_group', values='percent_of_total', aggfunc='max').sort_values(by='default', ascending=False)

_group           address_first   default
browser
Chrome                0.590412  0.591154
Mobile Safari         0.144358  0.142753
Yandex                0.117748  0.117904
Firefox               0.027148  0.028543
Samsung Browser       0.028387  0.028401
Opera                 0.025747  0.025199
MIUI Browser          0.018907  0.018143
Safari                0.016967  0.017800
Edge                  0.013197  0.013696
Chrome WebView        0.006518  0.006021
GSA                   0.004956  0.004339
WebKit                0.003124  0.003505
Android Browser       0.000754  0.000767
UCBrowser             0.000431  0.000706
Facebook              0.000215  0.000242
IE                    0.000108  0.000235
Opera Touch           0.000323  0.000182
Maxthon               0.000323  0.000121
Puffin                0.000054  0.000087
Chromium              0.000162  0.000067
Vivaldi                    NaN  0.000034
Mozilla                    NaN  0.000027
PaleMoon              0.000054  0.000013
Waterfox                   NaN  0.000013
QQBrowser                  NaN  0.000007
Slim                       NaN  0.000007
Brave                      NaN  0.000007
WeChat                     NaN  0.000007
Iceweasel                  NaN  0.000007
IceDragon                  NaN  0.000007
jasmine                    NaN  0.000007
IEMobile              0.000054       NaN
SeaMonkey             0.000054       NaN

`По браузерам перекоса нет, примерно равные группы`

## OS

In [412]:
sql = '''
    WITH conv AS (
          SELECT t.hit_at, t.anonymous_id, t._group, t.device_type, t.browser, t.os,
          MIN(lv.timestamp) AS Landing_Viewed_ts
          FROM AB_Test_Hit t
          INNER JOIN Landing_Viewed lv ON t.anonymous_id = lv.anonymous_id AND
          lv.timestamp >= t.hit_at
          GROUP BY t.hit_at, t.anonymous_id, t._group, t.device_type, t.browser, t.os),

          conv2 AS (
          SELECT c.hit_at, c.anonymous_id, c._group, c.device_type, c.browser, c.os,
          MAX(CASE
                  WHEN pa.anonymous_id IS NOT NULL THEN 1 ELSE 0
              END) AS product_added
          FROM conv c 
          LEFT JOIN Product_Added pa ON c.anonymous_id = pa.anonymous_id AND
          pa._timestamp >= c.Landing_Viewed_ts
          GROUP BY c.hit_at, c.anonymous_id, c._group, c.device_type, c.browser, c.os
          ),

          cnt_in_group AS
          (SELECT t._group, t.os, count(*) as cnt
          FROM conv2 t
          GROUP BY t._group, t.os)

          SELECT t.*, 
          SUM(t.cnt) OVER(PARTITION BY _group) AS total,
          CAST(t.cnt AS REAL)/CAST((SUM(t.cnt) OVER(PARTITION BY t._group)) AS REAL) AS percent_of_total
          FROM cnt_in_group t
          '''

In [415]:
t = select(sql)

In [417]:
t.pivot_table(index='os', columns='_group', values='percent_of_total', aggfunc='max').sort_values(by='default', ascending=False)

_group            address_first   default
os
Android                0.361110  0.360291
Windows                0.287423  0.293781
iOS                    0.179208  0.175278
Linux                  0.141234  0.139255
Mac OS                 0.029572  0.030016
Ubuntu                 0.001077  0.001049
Chromium OS            0.000108  0.000148
Windows Phone          0.000054  0.000054
Fedora                 0.000054  0.000047
Tizen                  0.000054  0.000040
PlayStation            0.000054  0.000034
Windows Phone OS       0.000054       NaN

# Вывод

Сначала у пользователя нужно запрашивать адрес, а потом предлагать выбрать уже доступные магазины с товарами. В таком случае конверсия добавления товара в корзину среди пользователей, которые видели лэндинг, выше, чем сначала выбирать магазин, а потом оказывается, что данный магазин не доступен по выбранному адресу