In [2]:
import pandas as pd

In [140]:
df= pd.read_excel('~/Desktop/an notebooks/работа 2026/отчет_трен.xlsx')

In [142]:
df = df.transpose()

In [144]:
df.columns = list(df.iloc[0,:])

In [146]:
df.drop('Дата', axis=0, inplace=True)

In [148]:
df.head()

,Площадка 1,Вид 1,Вид 2,Вид 3,Вид 4,Вид 5,Площадка 2,Вид 1,Вид 2,Вид 3,...,Вид 2,Вид 3,Вид 4,Вид 5,Площадка 5,Вид 1,Вид 2,Вид 3,Вид 4,Вид 5
2020-01-01 00:00:00,303,61,41,65,84,52,303,85,41,55,...,80,82,54,66,354,85,63,75,64,67
2020-01-02 00:00:00,280,43,46,73,64,54,280,56,57,40,...,53,53,72,57,338,65,70,52,64,87
2020-01-03 00:00:00,381,74,90,75,72,70,381,81,76,64,...,71,84,75,41,377,77,78,73,82,67
2020-01-04 00:00:00,307,47,65,85,48,62,307,62,53,84,...,59,84,90,83,319,65,88,83,43,40
2020-01-05 00:00:00,309,72,67,61,54,55,309,47,50,70,...,66,86,76,75,297,47,52,87,66,45

In [150]:
def fill_column(df):
    for i in df.columns:
        if 'Площадка' in i:
            df[i] = i
    return df

In [152]:
fill_column(df)

,Площадка 1,Вид 1,Вид 2,Вид 3,Вид 4,Вид 5,Площадка 2,Вид 1,Вид 2,Вид 3,...,Вид 2,Вид 3,Вид 4,Вид 5,Площадка 5,Вид 1,Вид 2,Вид 3,Вид 4,Вид 5
2020-01-01 00:00:00,Площадка 1,61,41,65,84,52,Площадка 2,85,41,55,...,80,82,54,66,Площадка 5,85,63,75,64,67
2020-01-02 00:00:00,Площадка 1,43,46,73,64,54,Площадка 2,56,57,40,...,53,53,72,57,Площадка 5,65,70,52,64,87
2020-01-03 00:00:00,Площадка 1,74,90,75,72,70,Площадка 2,81,76,64,...,71,84,75,41,Площадка 5,77,78,73,82,67
2020-01-04 00:00:00,Площадка 1,47,65,85,48,62,Площадка 2,62,53,84,...,59,84,90,83,Площадка 5,65,88,83,43,40
2020-01-05 00:00:00,Площадка 1,72,67,61,54,55,Площадка 2,47,50,70,...,66,86,76,75,Площадка 5,47,52,87,66,45
2020-01-06 00:00:00,Площадка 1,85,61,75,77,58,Площадка 2,43,54,84,...,62,77,67,87,Площадка 5,66,61,64,58,65
2020-01-07 00:00:00,Площадка 1,43,76,86,79,64,Площадка 2,58,44,78,...,40,41,53,55,Площадка 5,81,61,43,60,63

In [160]:
col_start = 0
col_end = 5
dataframes_list = []
for i in range(1, 6):
    df_i = df.iloc[:, col_start:col_end+1]
    for i in df_i.columns:
        if 'Площадка' in i:
            df_i.rename(columns={i: 'Площадка'}, inplace=True)
    dataframes_list.append(df_i)
    col_start += 5
    col_end += 5

In [162]:
dataframes_list[0]

                       Площадка Вид 1 Вид 2 Вид 3 Вид 4 Вид 5
2020-01-01 00:00:00  Площадка 1    61    41    65    84    52
2020-01-02 00:00:00  Площадка 1    43    46    73    64    54
2020-01-03 00:00:00  Площадка 1    74    90    75    72    70
2020-01-04 00:00:00  Площадка 1    47    65    85    48    62
2020-01-05 00:00:00  Площадка 1    72    67    61    54    55
2020-01-06 00:00:00  Площадка 1    85    61    75    77    58
2020-01-07 00:00:00  Площадка 1    43    76    86    79    64

In [182]:
df_all = pd.concat([dataframes_list[0],
                    dataframes_list[1],
                    dataframes_list[2],
                    dataframes_list[3],
                    dataframes_list[4]])
df_all['Общее_количество_на_дату'] = df_all.iloc[:, 1:].sum(axis=1)

In [184]:
df_all

              Площадка Вид 1 Вид 2 Вид 3 Вид 4 Вид 5 Общее_количество_на_дату
2020-01-01  Площадка 1    61    41    65    84    52                      303
2020-01-02  Площадка 1    43    46    73    64    54                      280
2020-01-03  Площадка 1    74    90    75    72    70                      381
2020-01-04  Площадка 1    47    65    85    48    62                      307
2020-01-05  Площадка 1    72    67    61    54    55                      309
2020-01-06  Площадка 1    85    61    75    77    58                      356
2020-01-07  Площадка 1    43    76    86    79    64                      348
2020-01-01  Площадка 2    85    41    55    59    52                      292
2020-01-02  Площадка 2    56    57    40    87    54                      294
2020-01-03  Площадка 2    81    76    64    45    70                      336
2020-01-04  Площадка 2    62    53    84    82    62                      343
2020-01-05  Площадка 2    47    50    70    43    55                      265
2020-01-06  Площадка 2    43    54    84    47    58                      286
2020-01-07  Площадка 2    58    44    78    45    64                      289
2020-01-01  Площадка 3    59    67    42    59    60                      287
2020-01-02  Площадка 3    60    67    74    87    40                      328
2020-01-03  Площадка 3    64    67    82    45    72                      330
2020-01-04  Площадка 3    76    83    82    82    60                      383
2020-01-05  Площадка 3    84    73    62    43    52                      314
2020-01-06  Площадка 3    68    44    71    47    73                      303
2020-01-07  Площадка 3    40    81    58    45    71                      295
2020-01-01  Площадка 4    52    80    42    63    78                      315
2020-01-02  Площадка 4    86    53    74    86    43                      342
2020-01-03  Площадка 4    78    71    82    79    45                      355
2020-01-04  Площадка 4    67    59    82    72    80                      360
2020-01-05  Площадка 4    64    66    62    70    55                      317
2020-01-06  Площадка 4    67    62    71    46    40                      286
2020-01-07  Площадка 4    90    40    58    63    43                      294
2020-01-01  Площадка 5    85    80    82    54    66                      367
2020-01-02  Площадка 5    65    53    53    72    57                      300
2020-01-03  Площадка 5    77    71    84    75    41                      348
2020-01-04  Площадка 5    65    59    84    90    83                      381
2020-01-05  Площадка 5    47    66    86    76    75                      350
2020-01-06  Площадка 5    66    62    77    67    87                      359
2020-01-07  Площадка 5    81    40    41    53    55                      270