In [3]:
import pandas as pd
import numpy as np

In [18]:
dict_array = {'age': [53, np.nan, 11, 18, 7],
              'name': ['Сергей', 'Маша', 'Ксюша', 'Аристарх', 'Соня'],
              'наличие авто': [True, True, False, np.nan, False],
              'марка авто': [np.nan, np.nan, np.nan, np.nan, np.nan,]
             }

df = pd.DataFrame(dict_array)

df

    age      name наличие авто  марка авто
0  53.0    Сергей         True         NaN
1   NaN      Маша         True         NaN
2  11.0     Ксюша        False         NaN
3  18.0  Аристарх          NaN         NaN
4   7.0      Соня        False         NaN

## Метод dropna()

In [20]:
df.dropna()

Empty DataFrame
Columns: [age, name, наличие авто, марка авто]
Index: []

In [52]:
df[['age', 'name', 'наличие авто']].dropna() # удаляет строки, в которых есть пропуски

    age    name наличие авто
0  53.0  Сергей         True
2  11.0   Ксюша        False
4   7.0    Соня        False

In [54]:
#df.dropna(axis = 0) # для строк
df.dropna(axis = 1) # для столбцов

       name
0    Сергей
1      Маша
2     Ксюша
3  Аристарх
4      Соня

In [56]:
# Аргумент how
df.dropna(how='all', axis = 1) # удаляет столбцы, в которых ВСЕ элементы - пропуски

    age      name наличие авто
0  53.0    Сергей         True
1   NaN      Маша         True
2  11.0     Ксюша        False
3  18.0  Аристарх          NaN
4   7.0      Соня        False

In [28]:
df

    age      name наличие авто  марка авто
0  53.0    Сергей         True         NaN
1   NaN      Маша         True         NaN
2  11.0     Ксюша        False         NaN
3  18.0  Аристарх          NaN         NaN
4   7.0      Соня        False         NaN

In [26]:
# Аргумент subset
df.dropna(subset=['age', 'наличие авто']) # удаляет те строки, для которых в указанных столбцах есть пропуски

    age    name наличие авто  марка авто
0  53.0  Сергей         True         NaN
2  11.0   Ксюша        False         NaN
4   7.0    Соня        False         NaN

In [30]:
df.dropna(subset=[1], axis=1) # удаляет те столбцы, для которых в указанных строках есть пропуски

       name наличие авто
0    Сергей         True
1      Маша         True
2     Ксюша        False
3  Аристарх          NaN
4      Соня        False

In [34]:
df.dropna(subset=['age', 'наличие авто'],
         inplace = True)

df

    age    name наличие авто  марка авто
0  53.0  Сергей         True         NaN
2  11.0   Ксюша        False         NaN
4   7.0    Соня        False         NaN

In [36]:
df = pd.DataFrame(dict_array)

df

    age      name наличие авто  марка авто
0  53.0    Сергей         True         NaN
1   NaN      Маша         True         NaN
2  11.0     Ксюша        False         NaN
3  18.0  Аристарх          NaN         NaN
4   7.0      Соня        False         NaN

In [38]:
df.fillna(value=6)

    age      name наличие авто  марка авто
0  53.0    Сергей         True         6.0
1   6.0      Маша         True         6.0
2  11.0     Ксюша        False         6.0
3  18.0  Аристарх            6         6.0
4   7.0      Соня        False         6.0

In [40]:
df.fillna(value={'age': 100,
                'наличие авто': 'еще думает',
                'марка авто': 'такая беленькая'}
         )

     age      name наличие авто       марка авто
0   53.0    Сергей         True  такая беленькая
1  100.0      Маша         True  такая беленькая
2   11.0     Ксюша        False  такая беленькая
3   18.0  Аристарх   еще думает  такая беленькая
4    7.0      Соня        False  такая беленькая

In [60]:
df.isna()

     age   name  наличие авто  марка авто
0  False  False         False        True
1   True  False         False        True
2  False  False         False        True
3  False  False          True        True
4  False  False         False        True

In [68]:
df['age'].isna()

0    False
1     True
2    False
3    False
4    False
Name: age, dtype: bool

In [70]:
df[~ df['age'].isna()]

    age      name наличие авто  марка авто
0  53.0    Сергей         True         NaN
2  11.0     Ксюша        False         NaN
3  18.0  Аристарх          NaN         NaN
4   7.0      Соня        False         NaN