In [2]:
import numpy as np
import pandas as pd

In [8]:
dict_array = {'age': [53, 53, 11, 18, 18, np.nan],
              'name': ['Сергей', 'Сергей', 'Ксюша', 'Аристарх', 'Соня', 'Соня'],
              'наличие авто': [True, True, False, True, False, True]}

In [12]:
df = pd.DataFrame(dict_array, 
                 index = ['row_0', 'row_1', 'row_2', 'row_3', 'row_4', 'row_5']
                 )
df

        age      name  наличие авто
row_0  53.0    Сергей          True
row_1  53.0    Сергей          True
row_2  11.0     Ксюша         False
row_3  18.0  Аристарх          True
row_4  18.0      Соня         False
row_5   NaN      Соня          True

In [14]:
#Метод unique
df['age'].unique()

array([53., 11., 18., nan])

In [16]:
#Метод nunique
df['age'].nunique()

3

In [20]:
df.nunique()

age             3
name            4
наличие авто    2
dtype: int64

In [22]:
df.value_counts() # считает количество встречающихся строк

age   name      наличие авто
53.0  Сергей    True            2
11.0  Ксюша     False           1
18.0  Аристарх  True            1
      Соня      False           1
Name: count, dtype: int64

In [24]:
df['наличие авто'].value_counts()

наличие авто
True     4
False    2
Name: count, dtype: int64

In [26]:
df.value_counts(['age', 'name'], dropna=False)

age   name
53.0  Сергей      2
11.0  Ксюша       1
18.0  Аристарх    1
      Соня        1
NaN   Соня        1
Name: count, dtype: int64

In [28]:
df.value_counts(['name'], normalize=True)

name
Сергей      0.333333
Соня        0.333333
Аристарх    0.166667
Ксюша       0.166667
Name: proportion, dtype: float64

In [32]:
df.sort_values('age')

        age      name  наличие авто
row_2  11.0     Ксюша         False
row_3  18.0  Аристарх          True
row_4  18.0      Соня         False
row_0  53.0    Сергей          True
row_1  53.0    Сергей          True
row_5   NaN      Соня          True

In [34]:
df.sort_values(['age', 'name'])

        age      name  наличие авто
row_2  11.0     Ксюша         False
row_3  18.0  Аристарх          True
row_4  18.0      Соня         False
row_0  53.0    Сергей          True
row_1  53.0    Сергей          True
row_5   NaN      Соня          True

In [36]:
df.sort_values('age', na_position='first')

        age      name  наличие авто
row_5   NaN      Соня          True
row_2  11.0     Ксюша         False
row_3  18.0  Аристарх          True
row_4  18.0      Соня         False
row_0  53.0    Сергей          True
row_1  53.0    Сергей          True

In [38]:
df.sort_values('age', na_position='first', inplace= True)
df

        age      name  наличие авто
row_5   NaN      Соня          True
row_2  11.0     Ксюша         False
row_3  18.0  Аристарх          True
row_4  18.0      Соня         False
row_0  53.0    Сергей          True
row_1  53.0    Сергей          True

In [44]:
df.sort_values('age', na_position='first', ascending=False, inplace= True) # ascending=False по убыванию
df

        age      name  наличие авто
row_5   NaN      Соня          True
row_0  53.0    Сергей          True
row_1  53.0    Сергей          True
row_3  18.0  Аристарх          True
row_4  18.0      Соня         False
row_2  11.0     Ксюша         False