In [2]:
import pandas as pd

## Функция concat()

In [13]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                    index= [0, 1, 2, 3])

In [15]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                    index= [1, 2, 3, 4])

In [17]:
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
                    index= [2, 3, 4, 5])

In [19]:
print(df1, end='\n\n')
print(df2, end='\n\n')
print(df3)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

    A   B   C   D
1  A4  B4  C4  D4
2  A5  B5  C5  D5
3  A6  B6  C6  D6
4  A7  B7  C7  D7

     A    B    C    D
2   A8   B8   C8   D8
3   A9   B9   C9   D9
4  A10  B10  C10  D10
5  A11  B11  C11  D11

In [21]:
pd.concat([df1, df2, df3])

     A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
1   A4   B4   C4   D4
2   A5   B5   C5   D5
3   A6   B6   C6   D6
4   A7   B7   C7   D7
2   A8   B8   C8   D8
3   A9   B9   C9   D9
4  A10  B10  C10  D10
5  A11  B11  C11  D11

In [23]:
pd.concat([df1, df2, df3], ignore_index=True)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [25]:
pd.concat([df1, df2, df3], axis = 1)

     A    B    C    D    A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1   A4   B4   C4   D4  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2   A5   B5   C5   D5   A8   B8   C8   D8
3   A3   B3   C3   D3   A6   B6   C6   D6   A9   B9   C9   D9
4  NaN  NaN  NaN  NaN   A7   B7   C7   D7  A10  B10  C10  D10
5  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

## Метод merge

In [34]:
df_1 = pd.DataFrame({'client_id': [100103, 21990, 455323, 1001003, 21990, 455323, 455323, 21990, 455323],
                    'product': ['product_2', 'product_2', 'product_1', 'product_1', 'product_1', 'product_3','product_3', 'product_3', 'product_6']})

In [36]:
df_2 = pd.DataFrame({'product': ['product_1', 'product_2', 'product_3', 'product_4', 'product_5'],
                     'price': [1000, 2000, 3000, 4000, 5000]})

In [38]:
print(df_1, end='\n\n')
print(df_2)

   client_id    product
0     100103  product_2
1      21990  product_2
2     455323  product_1
3    1001003  product_1
4      21990  product_1
5     455323  product_3
6     455323  product_3
7      21990  product_3
8     455323  product_6

     product  price
0  product_1   1000
1  product_2   2000
2  product_3   3000
3  product_4   4000
4  product_5   5000

In [40]:
df_1.merge(df_2, how = 'left') # элемент левого дф ищется в правом дф и возвращается

   client_id    product   price
0     100103  product_2  2000.0
1      21990  product_2  2000.0
2     455323  product_1  1000.0
3    1001003  product_1  1000.0
4      21990  product_1  1000.0
5     455323  product_3  3000.0
6     455323  product_3  3000.0
7      21990  product_3  3000.0
8     455323  product_6     NaN

In [42]:
df_1.merge(df_2, how = 'right') # элемент правого дф ищется в левом дф и возвращается

   client_id    product  price
0   455323.0  product_1   1000
1  1001003.0  product_1   1000
2    21990.0  product_1   1000
3   100103.0  product_2   2000
4    21990.0  product_2   2000
5   455323.0  product_3   3000
6   455323.0  product_3   3000
7    21990.0  product_3   3000
8        NaN  product_4   4000
9        NaN  product_5   5000

In [46]:
df_1.merge(df_2, how = 'inner') # эл-ты которые присутствуют в обоих дф

   client_id    product  price
0     100103  product_2   2000
1      21990  product_2   2000
2     455323  product_1   1000
3    1001003  product_1   1000
4      21990  product_1   1000
5     455323  product_3   3000
6     455323  product_3   3000
7      21990  product_3   3000

In [48]:
df_1.merge(df_2, how = 'outer') # все элементы

    client_id    product   price
0    455323.0  product_1  1000.0
1   1001003.0  product_1  1000.0
2     21990.0  product_1  1000.0
3    100103.0  product_2  2000.0
4     21990.0  product_2  2000.0
5    455323.0  product_3  3000.0
6    455323.0  product_3  3000.0
7     21990.0  product_3  3000.0
8         NaN  product_4  4000.0
9         NaN  product_5  5000.0
10   455323.0  product_6     NaN

In [50]:
df_1.merge(df_2, how = 'inner', on = 'product')

   client_id    product  price
0     100103  product_2   2000
1      21990  product_2   2000
2     455323  product_1   1000
3    1001003  product_1   1000
4      21990  product_1   1000
5     455323  product_3   3000
6     455323  product_3   3000
7      21990  product_3   3000

In [80]:
df_1 = pd.DataFrame({'client_id': [100103, 21990, 455323, 1001003, 21990, 455323, 455323, 21990, 455323],
                    'product': ['product_2', 'product_2', 'product_1', 'product_1', 'product_1', 'product_3','product_3', 'product_3', 'product_6'],
                    'color_prod': ['black', 'white', 'white', 'black', 'white', 'white', 'black', 'white', 'black']}
                   )

In [82]:
df_2 = pd.DataFrame({'product': ['product_1', 'product_2', 'product_3', 'product_4', 'product_5', 'product_1', 'product_2', 'product_3', 'product_4', 'product_5'],
                     'price': [1000, 2000, 3000, 4000, 5000, 1500, 2500, 3500, 4500, 5500],
                     'color_prod': ['black', 'black', 'white', 'white', 'black', 'white', 'white', 'white', 'black', 'white']})

In [62]:
df_1

   client_id    product color_prod
0     100103  product_2      black
1      21990  product_2      white
2     455323  product_1      white
3    1001003  product_1      black
4      21990  product_1      white
5     455323  product_3      white
6     455323  product_3      black
7      21990  product_3      white
8     455323  product_6      black

In [64]:
df_2

     product  price color_prod
0  product_1   1000      black
1  product_2   2000      black
2  product_3   3000      white
3  product_4   4000      white
4  product_5   5000      black
5  product_1   1500      white
6  product_2   2500      white
7  product_3   3500      white
8  product_4   4500      black
9  product_5   5500      white

In [66]:
df_1.merge(df_2, how='inner', on='product')

    client_id    product color_prod_x  price color_prod_y
0      100103  product_2        black   2000        black
1      100103  product_2        black   2500        white
2       21990  product_2        white   2000        black
3       21990  product_2        white   2500        white
4      455323  product_1        white   1000        black
5      455323  product_1        white   1500        white
6     1001003  product_1        black   1000        black
7     1001003  product_1        black   1500        white
8       21990  product_1        white   1000        black
9       21990  product_1        white   1500        white
10     455323  product_3        white   3000        white
11     455323  product_3        white   3500        white
12     455323  product_3        black   3000        white
13     455323  product_3        black   3500        white
14      21990  product_3        white   3000        white
15      21990  product_3        white   3500        white

In [68]:
df_1.merge(df_2, how='inner', on=['product', 'color_prod'])

   client_id    product color_prod  price
0     100103  product_2      black   2000
1      21990  product_2      white   2500
2     455323  product_1      white   1500
3    1001003  product_1      black   1000
4      21990  product_1      white   1500
5     455323  product_3      white   3000
6      21990  product_3      white   3000
7     455323  product_3      white   3500
8      21990  product_3      white   3500

In [84]:
df_1.rename(columns={'product': 'prod'}, inplace=True)
df_2.rename(columns={'color_prod': 'color'}, inplace=True)

In [86]:
df_1

   client_id       prod color_prod
0     100103  product_2      black
1      21990  product_2      white
2     455323  product_1      white
3    1001003  product_1      black
4      21990  product_1      white
5     455323  product_3      white
6     455323  product_3      black
7      21990  product_3      white
8     455323  product_6      black

In [88]:
df_2

     product  price  color
0  product_1   1000  black
1  product_2   2000  black
2  product_3   3000  white
3  product_4   4000  white
4  product_5   5000  black
5  product_1   1500  white
6  product_2   2500  white
7  product_3   3500  white
8  product_4   4500  black
9  product_5   5500  white

In [90]:
df_1.merge(df_2, how='left', 
           left_on=['prod', 'color_prod'],
           right_on=['product', 'color'])

    client_id       prod color_prod    product   price  color
0      100103  product_2      black  product_2  2000.0  black
1       21990  product_2      white  product_2  2500.0  white
2      455323  product_1      white  product_1  1500.0  white
3     1001003  product_1      black  product_1  1000.0  black
4       21990  product_1      white  product_1  1500.0  white
5      455323  product_3      white  product_3  3000.0  white
6      455323  product_3      white  product_3  3500.0  white
7      455323  product_3      black        NaN     NaN    NaN
8       21990  product_3      white  product_3  3000.0  white
9       21990  product_3      white  product_3  3500.0  white
10     455323  product_6      black        NaN     NaN    NaN

In [102]:
df_1 = pd.DataFrame({'product': ['product_1', 'product_2', 'product_3', 'product_4', 'product_5'],
                     'count': [10, 20, 30, 40, 50]})

In [104]:
df_2 = pd.DataFrame({'product': ['product_3', 'product_4', 'product_5', 'product_6', 'product_7'],
                     'count': [100, 200, 300, 400, 500]})

In [106]:
df_1.merge(df_2, how = 'outer', on='product')

     product  count_x  count_y
0  product_1     10.0      NaN
1  product_2     20.0      NaN
2  product_3     30.0    100.0
3  product_4     40.0    200.0
4  product_5     50.0    300.0
5  product_6      NaN    400.0
6  product_7      NaN    500.0

In [108]:
df_1.merge(df_2, 
           how = 'outer', 
           on='product',
          suffixes=['_shop_left', '_shop_right'])

     product  count_shop_left  count_shop_right
0  product_1             10.0               NaN
1  product_2             20.0               NaN
2  product_3             30.0             100.0
3  product_4             40.0             200.0
4  product_5             50.0             300.0
5  product_6              NaN             400.0
6  product_7              NaN             500.0