In [3]:
import numpy as np
import pandas as pd

## Метод Rolling

In [6]:
df_date = pd.DataFrame({'col_1': [0, 1, 2, 3, 4],
                       'col_2': [90, 91, 92, 93, 94]}
                      )
df_date

   col_1  col_2
0      0     90
1      1     91
2      2     92
3      3     93
4      4     94

In [14]:
a = df_date['col_2'].rolling(3).mean()
a

0     NaN
1     NaN
2    91.0
3    92.0
4    93.0
Name: col_2, dtype: float64

In [16]:
df_date.rolling(3)
for window in df_date.rolling(3):
    print(window, end ='\n\n')

   col_1  col_2
0      0     90

   col_1  col_2
0      0     90
1      1     91

   col_1  col_2
0      0     90
1      1     91
2      2     92

   col_1  col_2
1      1     91
2      2     92
3      3     93

   col_1  col_2
2      2     92
3      3     93
4      4     94

In [20]:
df_date.rolling(3).sum()

   col_1  col_2
0    NaN    NaN
1    NaN    NaN
2    3.0  273.0
3    6.0  276.0
4    9.0  279.0

In [31]:
print(df_date.rolling(3).mean(), end='\n\n')
print(df_date.rolling(3, min_periods=1).mean())

   col_1  col_2
0    NaN    NaN
1    NaN    NaN
2    1.0   91.0
3    2.0   92.0
4    3.0   93.0

   col_1  col_2
0    0.0   90.0
1    0.5   90.5
2    1.0   91.0
3    2.0   92.0
4    3.0   93.0

In [33]:
print(df_date.rolling(3).mean(), end='\n\n')
print(df_date.rolling(3, step=2).mean())

   col_1  col_2
0    NaN    NaN
1    NaN    NaN
2    1.0   91.0
3    2.0   92.0
4    3.0   93.0

   col_1  col_2
0    NaN    NaN
2    1.0   91.0
4    3.0   93.0

In [35]:
df_date.rolling(2).agg({'col_1': 'sum', 'col_2': 'mean'})

   col_1  col_2
0    NaN    NaN
1    1.0   90.5
2    3.0   91.5
3    5.0   92.5
4    7.0   93.5

In [39]:
df = pd.DataFrame({'sales': np.random.randint(0, 50, 100)},
                 index=pd.date_range('2023', periods=100))
df.head(10)

            sales
2023-01-01      4
2023-01-02     13
2023-01-03      5
2023-01-04     34
2023-01-05      0
2023-01-06     10
2023-01-07     32
2023-01-08     48
2023-01-09     15
2023-01-10      6

In [44]:
df_rolling = df.rolling(7, min_periods=1).agg(['sum', 'mean', 'max', 'min'])
df_rolling.head(10)

            sales
              sum       mean   max  min
2023-01-01    4.0   4.000000   4.0  4.0
2023-01-02   17.0   8.500000  13.0  4.0
2023-01-03   22.0   7.333333  13.0  4.0
2023-01-04   56.0  14.000000  34.0  4.0
2023-01-05   56.0  11.200000  34.0  0.0
2023-01-06   66.0  11.000000  34.0  0.0
2023-01-07   98.0  14.000000  34.0  0.0
2023-01-08  142.0  20.285714  48.0  0.0
2023-01-09  144.0  20.571429  48.0  0.0
2023-01-10  145.0  20.714286  48.0  0.0

In [51]:
df_rolling.reset_index(inplace=True)
df_rolling

   level_0      index  sales
                         sum       mean   max   min
0        0 2023-01-01    4.0   4.000000   4.0   4.0
1        1 2023-01-02   17.0   8.500000  13.0   4.0
2        2 2023-01-03   22.0   7.333333  13.0   4.0
3        3 2023-01-04   56.0  14.000000  34.0   4.0
4        4 2023-01-05   56.0  11.200000  34.0   0.0
..     ...        ...    ...        ...   ...   ...
95      95 2023-04-06  174.0  24.857143  48.0   1.0
96      96 2023-04-07  182.0  26.000000  48.0   1.0
97      97 2023-04-08  210.0  30.000000  48.0  14.0
98      98 2023-04-09  241.0  34.428571  48.0  20.0
99      99 2023-04-10  244.0  34.857143  48.0  20.0

[100 rows x 6 columns]

In [53]:
df_rolling['weekday'] = df_rolling['index'].dt.dayofweek
df_rolling

   level_0      index  sales                        weekday
                         sum       mean   max   min
0        0 2023-01-01    4.0   4.000000   4.0   4.0       6
1        1 2023-01-02   17.0   8.500000  13.0   4.0       0
2        2 2023-01-03   22.0   7.333333  13.0   4.0       1
3        3 2023-01-04   56.0  14.000000  34.0   4.0       2
4        4 2023-01-05   56.0  11.200000  34.0   0.0       3
..     ...        ...    ...        ...   ...   ...     ...
95      95 2023-04-06  174.0  24.857143  48.0   1.0       3
96      96 2023-04-07  182.0  26.000000  48.0   1.0       4
97      97 2023-04-08  210.0  30.000000  48.0  14.0       5
98      98 2023-04-09  241.0  34.428571  48.0  20.0       6
99      99 2023-04-10  244.0  34.857143  48.0  20.0       0

[100 rows x 7 columns]

In [57]:
df_rolling.loc[df_rolling['weekday'] == 6]

   level_0      index  sales                        weekday
                         sum       mean   max   min
0        0 2023-01-01    4.0   4.000000   4.0   4.0       6
7        7 2023-01-08  142.0  20.285714  48.0   0.0       6
14      14 2023-01-15  136.0  19.428571  39.0   6.0       6
21      21 2023-01-22  193.0  27.571429  48.0   5.0       6
28      28 2023-01-29  177.0  25.285714  48.0   1.0       6
35      35 2023-02-05  230.0  32.857143  42.0  20.0       6
42      42 2023-02-12  153.0  21.857143  41.0   1.0       6
49      49 2023-02-19  209.0  29.857143  42.0  15.0       6
56      56 2023-02-26  110.0  15.714286  43.0   0.0       6
63      63 2023-03-05  238.0  34.000000  49.0   7.0       6
70      70 2023-03-12  155.0  22.142857  44.0   2.0       6
77      77 2023-03-19  188.0  26.857143  48.0   6.0       6
84      84 2023-03-26  208.0  29.714286  49.0   6.0       6
91      91 2023-04-02  148.0  21.142857  45.0   1.0       6
98      98 2023-04-09  241.0  34.428571  48.0  20.0       6