In [3]:
import pandas as pd
import numpy as np

## Создание индексов строк и столбцов

In [17]:
list_index = list('qwqityui')
#list_index = [0, 1, 2, 3, 4, 5, 6, 7]
list_index

['q', 'w', 'q', 'i', 't', 'y', 'u', 'i']

In [19]:
index_data = pd.Index(list_index, # класс индекс
                      #dtype = np.float32,
                      name = 'rows'
                     )
index_data

Index(['q', 'w', 'q', 'i', 't', 'y', 'u', 'i'], dtype='object', name='rows')

In [25]:
column_data = pd.Index(['col_1', 'col_2', 'col_3'],
                      name = 'cols'
                      )
column_data

Index(['col_1', 'col_2', 'col_3'], dtype='object', name='cols')

In [36]:
df_data = pd.DataFrame({'col_1': [1, 4, 3, 5, 6, 3, 7, 13],
                        'col_2': [2, 5, 6, 7, 4, 3, 8, 9]},
                      index = index_data, # назначение имен
                      columns = column_data) # выборка
df_data

cols  col_1  col_2 col_3
rows
q         1      2   NaN
w         4      5   NaN
q         3      6   NaN
i         5      7   NaN
t         6      4   NaN
y         3      3   NaN
u         7      8   NaN
i        13      9   NaN

In [38]:
df = pd.DataFrame( {f'c_{i}': np.arange(1000)*i for i in range(100)} )
df

,c_0,c_1,c_2,c_3,c_4,c_5,c_6,c_7,c_8,c_9,...,c_90,c_91,c_92,c_93,c_94,c_95,c_96,c_97,c_98,c_99
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
2,0,2,4,6,8,10,12,14,16,18,...,180,182,184,186,188,190,192,194,196,198
3,0,3,6,9,12,15,18,21,24,27,...,270,273,276,279,282,285,288,291,294,297
4,0,4,8,12,16,20,24,28,32,36,...,360,364,368,372,376,380,384,388,392,396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,995,1990,2985,3980,4975,5970,6965,7960,8955,...,89550,90545,91540,92535,93530,94525,95520,96515,97510,98505
996,0,996,1992,2988,3984,4980,5976,6972,7968,8964,...,89640,90636,91632,92628,93624,94620,95616,96612,97608,98604
997,0,997,1994,2991,3988,4985,5982,6979,7976,8973,...,89730,90727,91724,92721,93718,94715,95712,96709,97706,98703
998,0,998,1996,2994,3992,4990,5988,6986,7984,8982,...,89820,90818,91816,92814,93812,94810,95808,96806,97804,98802
999,0,999,1998,2997,3996,4995,5994,6993,7992,8991,...,89910,90909,91908,92907,93906,94905,95904,96903,97902,98901

## Получение индексов Dataframe с помощью атрибутов index и columns

In [48]:
index = df.index # свойство df
index

RangeIndex(start=0, stop=1000, step=1)

In [50]:
columns = df.columns
columns

Index(['c_0', 'c_1', 'c_2', 'c_3', 'c_4', 'c_5', 'c_6', 'c_7', 'c_8', 'c_9',
       'c_10', 'c_11', 'c_12', 'c_13', 'c_14', 'c_15', 'c_16', 'c_17', 'c_18',
       'c_19', 'c_20', 'c_21', 'c_22', 'c_23', 'c_24', 'c_25', 'c_26', 'c_27',
       'c_28', 'c_29', 'c_30', 'c_31', 'c_32', 'c_33', 'c_34', 'c_35', 'c_36',
       'c_37', 'c_38', 'c_39', 'c_40', 'c_41', 'c_42', 'c_43', 'c_44', 'c_45',
       'c_46', 'c_47', 'c_48', 'c_49', 'c_50', 'c_51', 'c_52', 'c_53', 'c_54',
       'c_55', 'c_56', 'c_57', 'c_58', 'c_59', 'c_60', 'c_61', 'c_62', 'c_63',
       'c_64', 'c_65', 'c_66', 'c_67', 'c_68', 'c_69', 'c_70', 'c_71', 'c_72',
       'c_73', 'c_74', 'c_75', 'c_76', 'c_77', 'c_78', 'c_79', 'c_80', 'c_81',
       'c_82', 'c_83', 'c_84', 'c_85', 'c_86', 'c_87', 'c_88', 'c_89', 'c_90',
       'c_91', 'c_92', 'c_93', 'c_94', 'c_95', 'c_96', 'c_97', 'c_98', 'c_99'],
      dtype='object')

In [ ]:
#Заменить названия индексов столбцов
#df.columns = [указать нужные индексы столбцов]

## Преобразование индексов в список и массив Numpy с помощью метода to_list

In [61]:
#index.to_list()
#columns.to_list()

In [67]:
#index.to_numpy()
#columns.to_numpy()

## Уникальные значения и дубликаты в индексах

In [75]:
df_data = pd.DataFrame({'col_1': [1, 4, 3, 5, 6, 3, 7, 13],
                        'col_2': [2, 5, 6, 7, 4, 3, 8, 9]},
                      index = index_data, # назначение имен
                      columns = column_data) # выборка
df_data

cols  col_1  col_2 col_3
rows
q         1      2   NaN
w         4      5   NaN
q         3      6   NaN
i         5      7   NaN
t         6      4   NaN
y         3      3   NaN
u         7      8   NaN
i        13      9   NaN

In [84]:
index_data = df_data.index
print(f'{index_data}')
columns_data = df_data.columns
print(f'{columns_data}')

Index(['q', 'w', 'q', 'i', 't', 'y', 'u', 'i'], dtype='object', name='rows')
Index(['col_1', 'col_2', 'col_3'], dtype='object', name='cols')

In [86]:
index_data.unique() # уникальные значения индексов

Index(['q', 'w', 'i', 't', 'y', 'u'], dtype='object', name='rows')

In [96]:
columns_data.nunique() # количество уникальных значений

3

In [98]:
index_data.nunique()

6

In [100]:
columns_data.is_unique # True если все значения уникальны

True

In [106]:
print(index_data)
print(index_data.duplicated()) # False если элемент встречается впервые

Index(['q', 'w', 'q', 'i', 't', 'y', 'u', 'i'], dtype='object', name='rows')
[False False  True False False False False  True]

## Имя объекта с индексами. Переименовывание

In [108]:
index_data.name # возвращает имя индекса

'rows'

In [110]:
column_data.name

'cols'

In [116]:
index_data.name = 'rows_new' # изменяет имя индексов
df_data

cols      col_1  col_2 col_3
rows_new
q             1      2   NaN
w             4      5   NaN
q             3      6   NaN
i             5      7   NaN
t             6      4   NaN
y             3      3   NaN
u             7      8   NaN
i            13      9   NaN

In [128]:
# переименование меток столбцов
df_data.rename(columns = {'col_1': 'col_11',
                          'col_2': 'col_22',
                          'col_3': 'col_33',
                          'col_4': 'col_44'},
               inplace= True # изменения происходят в самом датафрейме
              )
df_data

cols      col_11  col_22 col_33
rows_new
q              1       2    NaN
w              4       5    NaN
q              3       6    NaN
i              5       7    NaN
t              6       4    NaN
y              3       3    NaN
u              7       8    NaN
i             13       9    NaN

## Пропуски в индексах

In [131]:
index = pd.Index([1, np.nan, 3, np.nan, 5])
index

Index([1.0, nan, 3.0, nan, 5.0], dtype='float64')

In [144]:
df_nan = pd.DataFrame(np.arange(5),
                      index = index,
                     columns = ['col_1'])
df_nan

     col_1
1.0      0
NaN      1
3.0      2
NaN      3
5.0      4

In [150]:
df_nan.index.hasnans # проверка наличия пропусков в индексах

True

In [152]:
df_nan.index.isna()

array([False,  True, False,  True, False])

In [158]:
df_nan.index.dropna() # удаляет пропуски в индексах, при этом не меняя индексацию

Index([1.0, 3.0, 5.0], dtype='float64')

In [7]:
2 % 2

0