In [4]:
import pandas as pd
import numpy as np

In [6]:
df = pd.DataFrame({'col_1':[5, 6, 6, 3, 7],
                  'col_2':[3, 2, 6, 3, 7],
                  'col_3':[5, 6, 3, 3, 4],
                  'col_4':[5, 6, 7, 8, 7],
                  'col_5':[5, 1, 6, 1, 5]}
                 )
df

   col_1  col_2  col_3  col_4  col_5
0      5      3      5      5      5
1      6      2      6      6      1
2      6      6      3      7      6
3      3      3      3      8      1
4      7      7      4      7      5

In [8]:
# установка значений столбца в качестве индексов строк
df.set_index('col_1')

       col_2  col_3  col_4  col_5
col_1
5          3      5      5      5
6          2      6      6      1
6          6      3      7      6
3          3      3      8      1
7          7      4      7      5

In [10]:
df.set_index(['col_1', 'col_2'],
             append = True,
             inplace = True
            )
df

               col_3  col_4  col_5
  col_1 col_2
0 5     3          5      5      5
1 6     2          6      6      1
2 6     6          3      7      6
3 3     3          3      8      1
4 7     7          4      7      5

In [12]:
df.reset_index(['col_2']) # превращает индексы строки в значения столбца

         col_2  col_3  col_4  col_5
  col_1
0 5          3      5      5      5
1 6          2      6      6      1
2 6          6      3      7      6
3 3          3      3      8      1
4 7          7      4      7      5

In [14]:
df.reset_index(inplace = True)
df

   level_0  col_1  col_2  col_3  col_4  col_5
0        0      5      3      5      5      5
1        1      6      2      6      6      1
2        2      6      6      3      7      6
3        3      3      3      3      8      1
4        4      7      7      4      7      5

## Доступ к данным с помощью индексов строк и столбцов

In [16]:
d = {'col_1':[5, 6, 6, 3, 7],
     'столбец_2':[3, 2, 6, 3, 7],
     'col_3':[5, 6, 3, 3, 4],
     'col_4':[5, 6, 7, 8, 7]
    }
df = pd.DataFrame(d)
df

   col_1  столбец_2  col_3  col_4
0      5          3      5      5
1      6          2      6      6
2      6          6      3      7
3      3          3      3      8
4      7          7      4      7

In [42]:
df['col_1']

0    5
1    6
2    6
3    3
4    7
Name: col_1, dtype: int64

In [20]:
df[['col_1']]

   col_1
0      5
1      6
2      6
3      3
4      7

In [30]:
#Выводит несколько столбцов
df[['col_1', 'col_4']]

   col_1  col_4
0      5      5
1      6      6
2      6      7
3      3      8
4      7      7

In [26]:
# добавляет новый столбец
df['new_col'] = 1
df

   col_1  столбец_2  col_3  col_4  new_col
0      5          3      5      5        1
1      6          2      6      6        1
2      6          6      3      7        1
3      3          3      3      8        1
4      7          7      4      7        1

In [111]:
#создает новый столбец со значениями из указанного столбца
df['new_col_2'] = df['col_3'] + df['col_4']
df

   col_1  столбец_2  col_3  col_4  new_col  new_col_2
0    100        100    100    100      100        200
1      6          2      6      6        1         12
2    100        100    100    100      100        200
3      3          3      3      8        1         11
4      7          7      4      7        1         11

In [32]:
df['new_col_3'] = np.arange(5)
df

   col_1  столбец_2  col_3  col_4  new_col  new_col_3
0      5          3      5      5        1          0
1      6          2      6      6        1          1
2      6          6      3      7        1          2
3      3          3      3      8        1          3
4      7          7      4      7        1          4

In [34]:
# удаление столбца
del df['new_col_3']
df

   col_1  столбец_2  col_3  col_4  new_col
0      5          3      5      5        1
1      6          2      6      6        1
2      6          6      3      7        1
3      3          3      3      8        1
4      7          7      4      7        1

In [38]:
df[[True, False, True, False, False]] # индексы строк

   col_1  столбец_2  col_3  col_4  new_col
0      5          3      5      5        1
2      6          6      3      7        1

In [119]:
df[[True, False, True, False, False]] = 100
df

   col_1  столбец_2  col_3  col_4  new_col  new_col_2
0    100        100    100    100      100        100
1      6          2      6      6        1         12
2    100        100    100    100      100        100
3      3          3      3      8        1         11
4      7          7      4      7        1         11

In [121]:
df[[True, False, True, False, False]][['столбец_2']]

   столбец_2
0        100
2        100

In [123]:
df.col_1

0    100
1      6
2    100
3      3
4      7
Name: col_1, dtype: int64